feat/imx8mp verdin
bao-project/bao-baremetal-guest pull request #4
Opened 2024-09-27 11:58 UTC by DavidMCerdeira

Add support for iMX8MP Verdin Dahlia platform

2024-10-04 14:46 UTC, josecm approved these changes, later dismissed

2024-10-04 15:04 UTC, danielRep requested changes

2024-10-04 15:04 UTC, danielRep commented on src/drivers/imx_uart/imx_uart.c
> +    uart->ubmr = ((24000000 / 2) / 115200);
```
    uart->ubmr = ((24000000 / 2) / 115200);
```

I would prefer to see the BaudRate and RefClk defined as a macro. I would also argue the same reasoning for all magic numbers and masks, though I'll leave that to your discretion

2026-03-30 16:03 UTC, danielRep reviewed
Don't forget this @DavidMCerdeira 
(trying stale workflow)

2026-04-17 13:08 UTC, DavidMCerdeira commented on src/drivers/imx_uart/imx_uart.c
> +    uart->ubmr = ((24000000 / 2) / 115200);
Please check

2026-04-21 19:05 UTC, danielRep approved these changes

2026-04-21 19:06 UTC, merged